[package]
name = "seedctl"
version = "0.1.2"
edition = "2024"

[dependencies]
bip39 = "2.2.2"
bitcoin = "0.32.8"
console = "0.16.2"
dialoguer = "0.12.0"
hex = "0.4.3"
rand = "0.9.2"
sha2 = "0.10.9"

[profile.release]
panic = "abort"
lto = true
strip = true
codegen-units = 1
